// Generated by tools/generate_assets.py - do not edit
#ifndef UI_FONTS_H
#define UI_FONTS_H

#ifdef LV_LVGL_H_INCLUDE_SIMPLE
#include "lvgl.h"
#else
#include "lvgl/lvgl.h"
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* 4 Standardized Segoe UI Semibold font sizes (User directive: min size 18) */
extern const lv_font_t ui_font_digits_62;
extern const lv_font_t ui_font_18;
extern const lv_font_t ui_font_24;
extern const lv_font_t ui_font_34;

/* Backward compatibility aliases */
#define ui_font_16 ui_font_18
#define ui_font_20 ui_font_24
#define ui_font_30 ui_font_34

#ifdef __cplusplus
}
#endif

#endif // UI_FONTS_H
