// Generated by tools/generate_assets.py - do not edit
#ifndef UI_ICONS_H
#define UI_ICONS_H

#ifdef LV_LVGL_H_INCLUDE_SIMPLE
#include "lvgl.h"
#else
#include "lvgl/lvgl.h"
#endif

#ifdef __cplusplus
extern "C" {
#endif

extern const lv_img_dsc_t ui_icon_home_32;
extern const lv_img_dsc_t ui_icon_chart_32;
extern const lv_img_dsc_t ui_icon_devices_32;
extern const lv_img_dsc_t ui_icon_home_24;
extern const lv_img_dsc_t ui_icon_chart_24;
extern const lv_img_dsc_t ui_icon_devices_24;
extern const lv_img_dsc_t ui_icon_sliders_24;
extern const lv_img_dsc_t ui_icon_radio_20;
extern const lv_img_dsc_t ui_icon_timer_20;
extern const lv_img_dsc_t ui_icon_air_28;
extern const lv_img_dsc_t ui_icon_thermometer_24;
extern const lv_img_dsc_t ui_icon_drop_24;
extern const lv_img_dsc_t ui_icon_purifier_24;
extern const lv_img_dsc_t ui_icon_fan_24;
extern const lv_img_dsc_t ui_icon_light_24;
extern const lv_img_dsc_t ui_icon_plug_24;
extern const lv_img_dsc_t ui_icon_heat_24;
extern const lv_img_dsc_t ui_icon_close_20;
extern const lv_img_dsc_t ui_icon_check_20;
extern const lv_img_dsc_t ui_icon_warning_20;

#ifdef __cplusplus
}
#endif

#endif // UI_ICONS_H
