#!/usr/bin/env python3
"""PNG -> LVGL v8 C array converter.

(The official LVGLImage.py only emits v9 formats, hence this small tool.)

Supported color formats (--cf):
  true_color        RGB565 little-endian, 2 bytes/px
  true_color_alpha  RGB565 LE + A8, 3 bytes/px
  indexed_8         256-color palette (BGRA 4B each) + 1 byte/px
  indexed_4         16-color palette (BGRA 4B each) + 4 bits/px, high nibble
                    first, rows padded to whole bytes
  alpha_4           alpha-only 4-bit (recolorable via style img_recolor)

Usage: python png2lvgl.py <in.png> <var_name> <out.c> [--cf indexed_8]
"""
import argparse

from PIL import Image

HEADER = """// Generated by tools/png2lvgl.py — do not edit by hand.
#ifdef LV_LVGL_H_INCLUDE_SIMPLE
#include "lvgl.h"
#else
#include "lvgl/lvgl.h"
#endif

#ifndef LV_ATTRIBUTE_MEM_ALIGN
#define LV_ATTRIBUTE_MEM_ALIGN
#endif

const LV_ATTRIBUTE_MEM_ALIGN uint8_t {name}_map[] = {{
"""

FOOTER = """}};

const lv_img_dsc_t {name} = {{
    .header.cf = {cf_enum},
    .header.always_zero = 0,
    .header.reserved = 0,
    .header.w = {w},
    .header.h = {h},
    .data_size = {size},
    .data = {name}_map,
}};
"""

CF_ENUM = {
    "true_color": "LV_IMG_CF_TRUE_COLOR",
    "true_color_alpha": "LV_IMG_CF_TRUE_COLOR_ALPHA",
    "indexed_8": "LV_IMG_CF_INDEXED_8BIT",
    "indexed_4": "LV_IMG_CF_INDEXED_4BIT",
    "alpha_4": "LV_IMG_CF_ALPHA_4BIT",
}


def rgb565(r, g, b):
    return ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)


def convert(img, cf):
    w, h = img.size
    out = bytearray()

    if cf in ("true_color", "true_color_alpha"):
        px = img.convert("RGBA").load()
        for y in range(h):
            for x in range(w):
                r, g, b, a = px[x, y]
                v = rgb565(r, g, b)
                out += bytes((v & 0xFF, v >> 8))
                if cf == "true_color_alpha":
                    out.append(a)

    elif cf in ("indexed_8", "indexed_4"):
        ncolors = 256 if cf == "indexed_8" else 16
        pal_img = img.convert("RGB").quantize(colors=ncolors, method=Image.MEDIANCUT)
        # getpalette() is only as long as the number of colors actually used,
        # which can be well under `ncolors` (e.g. a flat-palette image like
        # the dial face) — pad so the fixed-size palette table below never
        # index-errors on the unused tail entries.
        pal = pal_img.getpalette()
        pal = (pal + [0] * (ncolors * 3 - len(pal)))[: ncolors * 3]
        # Palette entries are lv_color32_t: byte order B, G, R, A in memory
        for i in range(ncolors):
            r, g, b = pal[i * 3], pal[i * 3 + 1], pal[i * 3 + 2]
            out += bytes((b, g, r, 0xFF))
        idx = pal_img.load()
        if cf == "indexed_8":
            for y in range(h):
                for x in range(w):
                    out.append(idx[x, y])
        else:
            stride = (w + 1) // 2
            for y in range(h):
                row = bytearray(stride)
                for x in range(w):
                    v = idx[x, y] & 0xF
                    if x % 2 == 0:
                        row[x // 2] |= v << 4  # high nibble first
                    else:
                        row[x // 2] |= v
                out += row

    elif cf == "alpha_4":
        px = img.convert("LA").load()
        stride = (w + 1) // 2
        for y in range(h):
            row = bytearray(stride)
            for x in range(w):
                a = px[x, y][1] >> 4
                if x % 2 == 0:
                    row[x // 2] |= a << 4
                else:
                    row[x // 2] |= a
            out += row

    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("input")
    ap.add_argument("name")
    ap.add_argument("output")
    ap.add_argument("--cf", default="indexed_8", choices=CF_ENUM.keys())
    args = ap.parse_args()

    img = Image.open(args.input)
    w, h = img.size
    data = convert(img, args.cf)

    lines = []
    for i in range(0, len(data), 16):
        chunk = data[i : i + 16]
        lines.append("    " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")

    with open(args.output, "w", newline="\n") as f:
        f.write(HEADER.format(name=args.name))
        f.write("\n".join(lines))
        f.write("\n")
        f.write(FOOTER.format(name=args.name, cf_enum=CF_ENUM[args.cf], w=w, h=h, size=len(data)))
    print(f"wrote {args.output}: {args.cf}, {w}x{h}, {len(data)} bytes")


if __name__ == "__main__":
    main()
